### ISSUE TITLE
Help function _getDS({ query, body })

### ISSUE THREAD

**Issue by Sureiyaaa** [genshin-kit/genshin-kit#26]
function _getDS({ query, body }) {
                  ^

TypeError: Cannot destructure property 'query' of 'undefined' as it is undefined.
    at GenshinKit._getDS (/home/sureiya/CCG/node_modules/genshin-kit/lib/module/_getDS.js:10:19)
    at GenshinKit._getHttpHeaders (/home/sureiya/CCG/node_modules/genshin-kit/lib/module/_getHttpHeaders.js:12:26)
    at GenshinKit.request (/home/sureiya/CCG/node_modules/genshin-kit/lib/module/request.js:20:23)
    at GenshinKit.getSpiralAbyss (/home/sureiya/CCG/node_modules/genshin-kit/lib/index.js:167:33)
    at GenshinKit.getCurrentAbyss (/home/sureiya/CCG/node_modules/genshin-kit/lib/index.js:204:21)
    at eval (eval at exec (/home/sureiya/CCG/Commands/Owner/Evalutate.js:38:20), <anonymous>:1:21)
    at EvaluateCommand.exec (/home/sureiya/CCG/Commands/Owner/Evalutate.js:38:20)
    at CommandHandler.runCommand (/home/sureiya/CCG/node_modules/discord-akairo/src/struct/commands/CommandHandler.js:768:39)
    at CommandHandler.handleDirectCommand (/home/sureiya/CCG/node_modules/discord-akairo/src/struct/commands/CommandHandler.js:439:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Sureiyaaa** [comment]
Everytime I'm going to use getUserInfo this error pops up

**Comment by Dragon-Fish** [comment]
Hi, can you:

1. Provide your Node.js version
2. Can you add the `--enable-source-maps` attribute when you execute your program? So we can get more detailed information.

Thank you

**Comment by Sureiyaaa** [comment]
Node.js Version: v16.7.0

**Comment by Sureiyaaa** [comment]
I added the --enable-source-maps what will I do now?

**Comment by Sureiyaaa** [comment]
This is the error I got rn I tried to run

this.client.genshin.getUserInfo("800151827").then(console.log, console.error)

TypeError: Cannot destructure property 'query' of 'undefined' as it is undefined.
    at GenshinKit._getDS (/home/sureiya/CCG/node_modules/genshin-kit/lib/module/_getDS.js:10:19)
    at GenshinKit._getHttpHeaders (/home/sureiya/CCG/node_modules/genshin-kit/lib/module/_getHttpHeaders.js:12:26)
    at GenshinKit.request (/home/sureiya/CCG/node_modules/genshin-kit/lib/module/request.js:20:23)
    at GenshinKit.getUserInfo (/home/sureiya/CCG/node_modules/genshin-kit/lib/index.js:91:33)
    at eval (eval at exec (/home/sureiya/CCG/Commands/Owner/Evalutate.js:38:20), <anonymous>:1:21)
    at EvaluateCommand.exec (/home/sureiya/CCG/Commands/Owner/Evalutate.js:38:20)
    at CommandHandler.runCommand (/home/sureiya/CCG/node_modules/discord-akairo/src/struct/commands/CommandHandler.js:768:39)
    at CommandHandler.handleDirectCommand (/home/sureiya/CCG/node_modules/discord-akairo/src/struct/commands/CommandHandler.js:439:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async CommandHandler.handle (/home/sureiya/CCG/node_modules/discord-akairo/src/struct/commands/CommandHandler.js:379:23)

**Comment by Dragon-Fish** [comment]
https://github.com/genshin-kit/genshin-kit/blob/b8bdce6bd9a80d70201f5ced0bd1c6c7cdf66180/src/module/_getHttpHeaders.ts#L9

Bug found: os request is missing params.

We are working on this issue. But it's midnight here. We will fix it in the morning.

**Comment by Dragon-Fish** [comment]
@AlPha5130 Need your help. Can you compile the latest code for testing?

**Comment by Sureiyaaa** [comment]
Thank you for looking this up I'll wait for the fix 👌

**Comment by AlPha5130** [comment]
There seems to be some other problems (not related to this topic though).

**Comment by Sureiyaaa** [comment]
ohh I hope you guys get to fix it good luck! and Thank you!

**Comment by AlPha5130** [comment]
Should be fixed in commits https://github.com/genshin-kit/genshin-kit/commit/32ed851f8bcb54bfd09621ab6c2b492b43e63436 and https://github.com/genshin-kit/genshin-kit/commit/bd810f0b126ecde26913c29ee6d30310b5dffe8c .

**Comment by Sureiyaaa** [comment]
Alright is the genshin-kit in npm.js site updated?

**Comment by Dragon-Fish** [comment]
`genshin-kit@2.4.1` now released
